export const ROUTES = {
    HOME: "/home",
    ABOUT_US: "/about-us",
    SERVICES: "/services",
    SERVICES_BUSINESS_DEVELOPMENT: "/services/business-development",
    SERVICES_BRAND_MANAGEMENT: "/services/brand-management",
    SERVICES_CAPACITY_BUILDING: "/services/capacity-building",
    SERVICES_MARKETING_CONSULTING: "/services/marketing-consulting",
    SERVICES_TRADE_INVESTMENT: "/services/trade-investment",
    BUSINESS_QUEST: "/business-quest",
    CONTACT: "/contact",
    BLOG: "/blog",
    JOIN_THE_WAITLIST: "/join-the-waitlist",
    PRIVACY_POLICY: "/privacy-policy",
    TERMS_AND_CONDITIONS: "/terms-and-conditions",

    CHAT_BOX: "/chat-box",
    AI_POWERED: "/ai-powered",
    SET_PASSWORD: "/set-password",
    RESET_PASSWORD: "/reset-password",
    FORGET_PASSWORD: "/forget-password",
    VERIFY_TOKEN: "/verify-token",
    LOGIN: "/login",
    BOOK_CONSULTATION: "https://calendar.app.google/6QmW8c2DK6ySefYD7",
}